version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    
    steps:
      - checkout
      - run:
          name: Install Salesforce DX
          command: |
              openssl aes-256-cbc -k $KEY -in assets/server.key.enc -out assets/server.key -d
              export SFDX_AUTOUPDATE_DISABLE=true
              export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
              export SFDX_DOMAIN_RETRY=300
              sudo npm install sfdx-cli --global
              sfdx update
              sfdx --version
              sfdx plugins --core
      - run: 
          name: Create Scratch Org
          command: |
              sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key --username $USERNAME --setdefaultdevhubusername -a DevHub
              sfdx force:org:create -v DevHub -s -f config/project-scratch-def.json -a scratch
      - run: 
          name: Push Source
          command: |
             sfdx force:source:push -u scratch
      - run:
          name: Run Apex Tests
          command: |
              mkdir ~/apex_tests
              sfdx force:apex:test:run -u scratch -r junit -d ~/apex_tests > /dev/null
      - run: 
          name: Clean Up
          when: always
          command: |
              sfdx force:org:delete -u scratch -p
              rm assets/server.key
              cd ~/apex_tests
              rm *.json *-junit.xml *.txt
      - store_artifacts:
          path: ~/apex_tests
      - store_test_results:
          path: ~/apex_tests
